<?php
// Admin-managed config overrides.
// Generated by admin/config.php — do not edit by hand.
// define() calls here win over defaults in includes/plan_limits.php
// and config.php because this file is loaded first.
