<?php
/**
 * includes/site_templates.php — Template definitions for generated websites.
 * Each template defines a visual identity (colors, fonts, layout style) used
 * by the site builder in includes/site_builder.php to render multi-page sites.
 */

const SITE_TEMPLATES = [
    'modern' => [
        'label' => 'Modern Emerald',
        'description' => 'Clean, spacious, rounded corners. Great for contractors and home services.',
        'category' => 'Professional',
        'primary' => '#10B981',
        'secondary' => '#0F172A',
        'accent' => '#ECFDF5',
        'text' => '#1E293B',
        'font' => "'Inter', system-ui, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap',
        'hero_style' => 'centered',
        'radius' => '16px',
    ],
    'classic' => [
        'label' => 'Classic Navy',
        'description' => 'Traditional, trustworthy, serif headings. Great for law, finance, medical.',
        'category' => 'Professional',
        'primary' => '#1E3A8A',
        'secondary' => '#0F172A',
        'accent' => '#EFF6FF',
        'text' => '#1E293B',
        'font' => "'Georgia', 'Times New Roman', serif",
        'font_url' => null,
        'hero_style' => 'split',
        'radius' => '4px',
    ],
    'bold' => [
        'label' => 'Bold Orange',
        'description' => 'High-energy, big type, strong contrast. Great for fitness, food, events.',
        'category' => 'Vibrant',
        'primary' => '#F97316',
        'secondary' => '#111827',
        'accent' => '#FFF7ED',
        'text' => '#111827',
        'font' => "'Poppins', system-ui, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800&display=swap',
        'hero_style' => 'centered',
        'radius' => '999px',
    ],
    'minimal' => [
        'label' => 'Minimal Mono',
        'description' => 'Black, white, lots of whitespace. Great for design studios, photographers.',
        'category' => 'Minimal',
        'primary' => '#111827',
        'secondary' => '#F9FAFB',
        'accent' => '#F3F4F6',
        'text' => '#111827',
        'font' => "'Helvetica Neue', Arial, sans-serif",
        'font_url' => null,
        'hero_style' => 'left',
        'radius' => '0px',
    ],
    'luxury' => [
        'label' => 'Luxury Gold',
        'description' => 'Dark background, gold accents, elegant serif. Great for salons, jewelers, high-end retail.',
        'category' => 'Premium',
        'primary' => '#D4AF37',
        'secondary' => '#0A0A0A',
        'accent' => '#1A1A1A',
        'text' => '#F5F5F5',
        'font' => "'Playfair Display', Georgia, serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700;800&display=swap',
        'hero_style' => 'centered-dark',
        'radius' => '2px',
        'dark' => true,
    ],
    'vibrant' => [
        'label' => 'Vibrant Coral',
        'description' => 'Playful gradients, rounded shapes. Great for cafes, salons, boutiques.',
        'category' => 'Vibrant',
        'primary' => '#FB7185',
        'secondary' => '#4C1D95',
        'accent' => '#FFF1F2',
        'text' => '#1E1B4B',
        'font' => "'Nunito', system-ui, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap',
        'hero_style' => 'centered',
        'radius' => '24px',
    ],
    'corporate' => [
        'label' => 'Corporate Slate',
        'description' => 'Sharp, structured, data-forward. Great for consultants, agencies, B2B.',
        'category' => 'Professional',
        'primary' => '#334155',
        'secondary' => '#0F172A',
        'accent' => '#F1F5F9',
        'text' => '#0F172A',
        'font' => "'Roboto', system-ui, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap',
        'hero_style' => 'split',
        'radius' => '8px',
    ],
    'earthy' => [
        'label' => 'Earthy Sage',
        'description' => 'Natural greens and browns, organic feel. Great for landscaping, wellness, farms.',
        'category' => 'Natural',
        'primary' => '#65A30D',
        'secondary' => '#292524',
        'accent' => '#F7FEE7',
        'text' => '#292524',
        'font' => "'Merriweather', Georgia, serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700;900&display=swap',
        'hero_style' => 'left',
        'radius' => '12px',
    ],
    'ocean' => [
        'label' => 'Ocean Blue',
        'description' => 'Fresh, breezy, coastal blues. Great for cleaning, marine, travel, pools.',
        'category' => 'Fresh',
        'primary' => '#0891B2',
        'secondary' => '#083344',
        'accent' => '#ECFEFF',
        'text' => '#0C4A6E',
        'font' => "'Quicksand', system-ui, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600;700&display=swap',
        'hero_style' => 'centered',
        'radius' => '20px',
    ],
    'industrial' => [
        'label' => 'Industrial Steel',
        'description' => 'Rugged, high-contrast, angular. Great for construction, auto, manufacturing.',
        'category' => 'Bold',
        'primary' => '#EAB308',
        'secondary' => '#18181B',
        'accent' => '#27272A',
        'text' => '#F4F4F5',
        'font' => "'Oswald', Impact, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&display=swap',
        'hero_style' => 'centered-dark',
        'radius' => '2px',
        'dark' => true,
    ],
    'pastel' => [
        'label' => 'Pastel Lavender',
        'description' => 'Soft, calm, friendly. Great for childcare, therapy, beauty, boutique retail.',
        'category' => 'Soft',
        'primary' => '#A78BFA',
        'secondary' => '#F5F3FF',
        'accent' => '#EDE9FE',
        'text' => '#4C1D95',
        'font' => "'Comfortaa', system-ui, sans-serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;600;700&display=swap',
        'hero_style' => 'centered',
        'radius' => '28px',
    ],
    'monochrome' => [
        'label' => 'Monochrome Editorial',
        'description' => 'Magazine-style layout, big serif type, black and white photography feel.',
        'category' => 'Minimal',
        'primary' => '#18181B',
        'secondary' => '#FAFAFA',
        'accent' => '#E4E4E7',
        'text' => '#18181B',
        'font' => "'Libre Baskerville', Georgia, serif",
        'font_url' => 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap',
        'hero_style' => 'left',
        'radius' => '0px',
    ],
];

function get_site_template(string $key): array
{
    return SITE_TEMPLATES[$key] ?? SITE_TEMPLATES['modern'];
}

function get_all_site_templates(): array
{
    return SITE_TEMPLATES;
}
