<?php
/**
 * includes/site_templates.php
 * Template definitions for generated websites (25 total).
 */

const SITE_TEMPLATES = [

    // ── Professional ────────────────────────────────────────────────────────
    'modern' => [
        'label'       => 'Modern Emerald',
        'description' => 'Clean, spacious, rounded corners. Great for contractors and home services.',
        'category'    => 'Professional',
        'primary'     => '#10B981',
        'secondary'   => '#0F172A',
        'accent'      => '#ECFDF5',
        'text'        => '#1E293B',
        'font'        => "'Inter', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '16px',
    ],
    'classic' => [
        'label'       => 'Classic Navy',
        'description' => 'Traditional, trustworthy, serif headings. Great for law, finance, medical.',
        'category'    => 'Professional',
        'primary'     => '#1E3A8A',
        'secondary'   => '#0F172A',
        'accent'      => '#EFF6FF',
        'text'        => '#1E293B',
        'font'        => "'Georgia', 'Times New Roman', serif",
        'font_url'    => null,
        'hero_style'  => 'split',
        'radius'      => '4px',
    ],
    'corporate' => [
        'label'       => 'Corporate Slate',
        'description' => 'Sharp, structured, data-forward. Great for consultants, agencies, B2B.',
        'category'    => 'Professional',
        'primary'     => '#334155',
        'secondary'   => '#0F172A',
        'accent'      => '#F1F5F9',
        'text'        => '#0F172A',
        'font'        => "'Roboto', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap',
        'hero_style'  => 'split',
        'radius'      => '8px',
    ],
    'executive' => [
        'label'       => 'Executive Midnight',
        'description' => 'Dark navy with silver accents, authoritative serif. Perfect for C-suite, brokerages, law.',
        'category'    => 'Professional',
        'primary'     => '#94A3B8',
        'secondary'   => '#020617',
        'accent'      => '#0F172A',
        'text'        => '#E2E8F0',
        'font'        => "'Cormorant Garamond', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '2px',
        'dark'        => true,
    ],
    'saas' => [
        'label'       => 'SaaS Indigo',
        'description' => 'Gradient hero, clean grid, product-focused. Great for tech startups, software, apps.',
        'category'    => 'Professional',
        'primary'     => '#6366F1',
        'secondary'   => '#0F0F23',
        'accent'      => '#EEF2FF',
        'text'        => '#1E1B4B',
        'font'        => "'DM Sans', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '12px',
        'dark'        => true,
    ],
    'agency' => [
        'label'       => 'Agency Black',
        'description' => 'All-black, bold white type, accent red. Great for marketing agencies, PR, media.',
        'category'    => 'Professional',
        'primary'     => '#EF4444',
        'secondary'   => '#000000',
        'accent'      => '#0D0D0D',
        'text'        => '#FAFAFA',
        'font'        => "'Bebas Neue', Impact, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '0px',
        'dark'        => true,
    ],

    // ── Vibrant ──────────────────────────────────────────────────────────────
    'bold' => [
        'label'       => 'Bold Orange',
        'description' => 'High-energy, big type, strong contrast. Great for fitness, food, events.',
        'category'    => 'Vibrant',
        'primary'     => '#F97316',
        'secondary'   => '#111827',
        'accent'      => '#FFF7ED',
        'text'        => '#111827',
        'font'        => "'Poppins', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '999px',
    ],
    'vibrant' => [
        'label'       => 'Vibrant Coral',
        'description' => 'Playful gradients, rounded shapes. Great for cafes, salons, boutiques.',
        'category'    => 'Vibrant',
        'primary'     => '#FB7185',
        'secondary'   => '#4C1D95',
        'accent'      => '#FFF1F2',
        'text'        => '#1E1B4B',
        'font'        => "'Nunito', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '24px',
    ],
    'sunset' => [
        'label'       => 'Sunset Gradient',
        'description' => 'Warm purple-to-pink gradient, modern type. Great for events, creative agencies, nightlife.',
        'category'    => 'Vibrant',
        'primary'     => '#EC4899',
        'secondary'   => '#1C0033',
        'accent'      => '#FDF2F8',
        'text'        => '#1C0033',
        'font'        => "'Syne', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '18px',
        'dark'        => true,
    ],
    'neon' => [
        'label'       => 'Neon Dark',
        'description' => 'Pure black base, electric green neon accents. Great for gaming, tech, nightclubs, barbers.',
        'category'    => 'Vibrant',
        'primary'     => '#39FF14',
        'secondary'   => '#000000',
        'accent'      => '#0A0A0A',
        'text'        => '#E5E5E5',
        'font'        => "'Rajdhani', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '4px',
        'dark'        => true,
    ],
    'tropical' => [
        'label'       => 'Tropical Teal',
        'description' => 'Bright teal and yellow, island vibe. Great for travel, tours, spas, resorts.',
        'category'    => 'Vibrant',
        'primary'     => '#06B6D4',
        'secondary'   => '#042F2E',
        'accent'      => '#F0FDFA',
        'text'        => '#134E4A',
        'font'        => "'Quicksand', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600;700&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '20px',
    ],

    // ── Premium ──────────────────────────────────────────────────────────────
    'luxury' => [
        'label'       => 'Luxury Gold',
        'description' => 'Dark background, gold accents, elegant serif. Great for salons, jewelers, high-end retail.',
        'category'    => 'Premium',
        'primary'     => '#D4AF37',
        'secondary'   => '#0A0A0A',
        'accent'      => '#1A1A1A',
        'text'        => '#F5F5F5',
        'font'        => "'Playfair Display', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '2px',
        'dark'        => true,
    ],
    'rose_gold' => [
        'label'       => 'Rose Gold',
        'description' => 'Blush pinks and warm copper tones, refined serif. Great for bridal, beauty, luxury skincare.',
        'category'    => 'Premium',
        'primary'     => '#C2748A',
        'secondary'   => '#1A0A0E',
        'accent'      => '#FFF0F3',
        'text'        => '#2D1018',
        'font'        => "'Cormorant Garamond', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '6px',
    ],
    'obsidian' => [
        'label'       => 'Obsidian',
        'description' => 'Deep charcoal with ice-blue highlights, angular grid. Great for architecture, high-end contractors.',
        'category'    => 'Premium',
        'primary'     => '#38BDF8',
        'secondary'   => '#0C0C0F',
        'accent'      => '#111827',
        'text'        => '#F0F9FF',
        'font'        => "'Space Grotesk', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '6px',
        'dark'        => true,
    ],

    // ── Natural ──────────────────────────────────────────────────────────────
    'earthy' => [
        'label'       => 'Earthy Sage',
        'description' => 'Natural greens and browns, organic feel. Great for landscaping, wellness, farms.',
        'category'    => 'Natural',
        'primary'     => '#65A30D',
        'secondary'   => '#292524',
        'accent'      => '#F7FEE7',
        'text'        => '#292524',
        'font'        => "'Merriweather', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700;900&display=swap',
        'hero_style'  => 'left',
        'radius'      => '12px',
    ],
    'terracotta' => [
        'label'       => 'Terracotta Warm',
        'description' => 'Warm clay and cream tones, hand-crafted feel. Great for bakeries, pottery, artisan shops.',
        'category'    => 'Natural',
        'primary'     => '#C2693A',
        'secondary'   => '#2C1810',
        'accent'      => '#FDF6F0',
        'text'        => '#2C1810',
        'font'        => "'Lora', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Lora:wght@400;600;700&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '10px',
    ],
    'forest' => [
        'label'       => 'Forest Deep',
        'description' => 'Rich hunter green on cream, woodsy texture feel. Great for outdoor guides, cabins, eco-tourism.',
        'category'    => 'Natural',
        'primary'     => '#166534',
        'secondary'   => '#052E16',
        'accent'      => '#F0FDF4',
        'text'        => '#14532D',
        'font'        => "'Cabin', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Cabin:wght@400;600;700&display=swap',
        'hero_style'  => 'left',
        'radius'      => '8px',
    ],

    // ── Minimal ──────────────────────────────────────────────────────────────
    'minimal' => [
        'label'       => 'Minimal Mono',
        'description' => 'Black, white, lots of whitespace. Great for design studios, photographers.',
        'category'    => 'Minimal',
        'primary'     => '#111827',
        'secondary'   => '#F9FAFB',
        'accent'      => '#F3F4F6',
        'text'        => '#111827',
        'font'        => "'Helvetica Neue', Arial, sans-serif",
        'font_url'    => null,
        'hero_style'  => 'left',
        'radius'      => '0px',
    ],
    'monochrome' => [
        'label'       => 'Monochrome Editorial',
        'description' => 'Magazine-style layout, big serif type, black and white photography feel.',
        'category'    => 'Minimal',
        'primary'     => '#18181B',
        'secondary'   => '#FAFAFA',
        'accent'      => '#E4E4E7',
        'text'        => '#18181B',
        'font'        => "'Libre Baskerville', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap',
        'hero_style'  => 'left',
        'radius'      => '0px',
    ],
    'nordic' => [
        'label'       => 'Nordic Clean',
        'description' => 'Off-white, cool greys, wide tracking. Great for architecture, interior design, real estate.',
        'category'    => 'Minimal',
        'primary'     => '#64748B',
        'secondary'   => '#F8FAFC',
        'accent'      => '#F1F5F9',
        'text'        => '#0F172A',
        'font'        => "'Jost', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500;600;700&display=swap',
        'hero_style'  => 'left',
        'radius'      => '0px',
    ],
    'paper' => [
        'label'       => 'Paper & Ink',
        'description' => 'Warm ivory background, dark ink type, handwritten accent. Great for writers, tutors, coaches.',
        'category'    => 'Minimal',
        'primary'     => '#92400E',
        'secondary'   => '#1C1917',
        'accent'      => '#FEFCE8',
        'text'        => '#1C1917',
        'font'        => "'Lora', Georgia, serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Lora:wght@400;600;700&display=swap',
        'hero_style'  => 'left',
        'radius'      => '4px',
    ],

    // ── Soft ─────────────────────────────────────────────────────────────────
    'pastel' => [
        'label'       => 'Pastel Lavender',
        'description' => 'Soft, calm, friendly. Great for childcare, therapy, beauty, boutique retail.',
        'category'    => 'Soft',
        'primary'     => '#A78BFA',
        'secondary'   => '#F5F3FF',
        'accent'      => '#EDE9FE',
        'text'        => '#4C1D95',
        'font'        => "'Comfortaa', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;600;700&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '28px',
    ],
    'sky' => [
        'label'       => 'Sky Breeze',
        'description' => 'Airy light blue, open feel, rounded. Great for healthcare, dentists, cleaning services.',
        'category'    => 'Soft',
        'primary'     => '#0EA5E9',
        'secondary'   => '#F0F9FF',
        'accent'      => '#E0F2FE',
        'text'        => '#0C4A6E',
        'font'        => "'Nunito', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '20px',
    ],
    'mint' => [
        'label'       => 'Mint Fresh',
        'description' => 'Cool mint green on white, clean and welcoming. Great for spas, yoga, health coaches.',
        'category'    => 'Soft',
        'primary'     => '#34D399',
        'secondary'   => '#F0FDF9',
        'accent'      => '#CCFBF1',
        'text'        => '#064E3B',
        'font'        => "'Plus Jakarta Sans', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '16px',
    ],

    // ── Bold ─────────────────────────────────────────────────────────────────
    'industrial' => [
        'label'       => 'Industrial Steel',
        'description' => 'Rugged, high-contrast, angular. Great for construction, auto, manufacturing.',
        'category'    => 'Bold',
        'primary'     => '#EAB308',
        'secondary'   => '#18181B',
        'accent'      => '#27272A',
        'text'        => '#F4F4F5',
        'font'        => "'Oswald', Impact, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '2px',
        'dark'        => true,
    ],
    'crimson' => [
        'label'       => 'Crimson Power',
        'description' => 'Deep red and black, aggressive energy. Great for gyms, martial arts, sports brands.',
        'category'    => 'Bold',
        'primary'     => '#DC2626',
        'secondary'   => '#0A0A0A',
        'accent'      => '#1A0000',
        'text'        => '#FAFAFA',
        'font'        => "'Barlow Condensed', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered-dark',
        'radius'      => '4px',
        'dark'        => true,
    ],

    // ── Fresh ─────────────────────────────────────────────────────────────────
    'ocean' => [
        'label'       => 'Ocean Blue',
        'description' => 'Fresh, breezy, coastal blues. Great for cleaning, marine, travel, pools.',
        'category'    => 'Fresh',
        'primary'     => '#0891B2',
        'secondary'   => '#083344',
        'accent'      => '#ECFEFF',
        'text'        => '#0C4A6E',
        'font'        => "'Quicksand', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600;700&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '20px',
    ],
    'citrus' => [
        'label'       => 'Citrus Pop',
        'description' => 'Bright lemon-lime, punchy and upbeat. Great for juice bars, food trucks, pop-ups.',
        'category'    => 'Fresh',
        'primary'     => '#84CC16',
        'secondary'   => '#1A2E05',
        'accent'      => '#F7FEE7',
        'text'        => '#1A2E05',
        'font'        => "'Plus Jakarta Sans', system-ui, sans-serif",
        'font_url'    => 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap',
        'hero_style'  => 'centered',
        'radius'      => '16px',
    ],
];

function get_site_template(string $key): array
{
    return SITE_TEMPLATES[$key] ?? SITE_TEMPLATES['modern'];
}

function get_all_site_templates(): array
{
    return SITE_TEMPLATES;
}
