<?php
/**
 * api/support-file.php
 *
 * GET ?id=<attachment id>
 *
 * The only way to read a support attachment. The files live under storage/support/,
 * which storage/.htaccess denies, so a leaked path cannot serve them — and this
 * endpoint refuses a request from anyone who is not the ticket's owner or an admin.
 *
 * Images are served INLINE so a screenshot opens in the thread, everything else is
 * an attachment with its original filename. Either way the response is private and
 * uncached: a ticket is a private conversation, and a shared machine's disk cache is
 * not the place to leave one.
 */
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/error_logger.php';
require_once __DIR__ . '/../includes/support.php';

api_bootstrap();

if (!is_logged_in()) {
    _sf_fail('Not logged in', 401);
}

$user = current_user();
$uid  = (int)($user['id'] ?? 0);
$id   = isset($_GET['id']) ? (int)$_GET['id'] : 0;
if ($id <= 0) {
    _sf_fail('Invalid id', 400);
}

try {
    $pdo  = get_platform_db();
    $stmt = $pdo->prepare('SELECT * FROM support_attachments WHERE id = ? LIMIT 1');
    $stmt->execute([$id]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
} catch (\Throwable $e) {
    log_error('support_file_lookup', $e, ['uid' => $uid, 'attachment_id' => $id]);
    _sf_fail('Could not load that file', 500);
}

if (!$row) {
    _sf_fail('File not found', 404);
}

// Two doors: the account that opened the ticket, or an administrator. The
// attachment's own user_id is the ticket owner, so this is the same test the ticket
// list uses rather than a second, possibly-wrong rule.
$isOwner = (int)($row['user_id'] ?? 0) === $uid;
$isAdmin = !empty($user['is_admin']);
if (!$isOwner && !$isAdmin) {
    _sf_fail('File not found', 404);
}

$root = dirname(__DIR__);
$rel  = ltrim((string)($row['stored_path'] ?? ''), '/');
$path = $root . '/' . $rel;

// Belt and braces against a stored path that ever escapes the upload root: the
// stored name is random and generated by us, so this should be impossible, and it
// must stay impossible.
$base = realpath($root . '/' . SUPPORT_UPLOAD_DIR_REL);
$real = realpath($path);
if ($base === false || $real === false || !str_starts_with($real, $base) || !is_file($real)) {
    _sf_fail('File is no longer on the server', 410);
}

$mime = (string)($row['mime_type'] ?? 'application/octet-stream');
$name = support_attachment_name_clean((string)($row['original_name'] ?? 'attachment'));

header('Content-Type: ' . $mime);
header('Content-Length: ' . filesize($real));
header('Content-Disposition: '
    . (support_attachment_is_image($mime) ? 'inline' : 'attachment')
    . '; filename="' . str_replace('"', '', $name) . '"');
header('Cache-Control: private, no-store, max-age=0');
header('X-Content-Type-Options: nosniff');
header('X-Robots-Tag: noindex');

readfile($real);
exit;

function _sf_fail(string $msg, int $code = 400): void
{
    http_response_code($code);
    header('Content-Type: text/plain; charset=utf-8');
    echo $msg;
    exit;
}
